# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tatenda Katema portfolio site!
email: tkatema5@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  welcome to my portfolio site!
baseurl: "/my_blog" # the subpath of your site, e.g. /blog
url: "https://katman-generation.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: KatemaTatenda
github_username:  katman-Generation

# Fields minima uses, but are not defaulted with the jekyll new command.
# Author is the default for post, the Atom feed, and i used in the footer

author: Tatenda Katema
linkedin_username: tatenda-katema
facebook_username: KG Foundation

#copyright: company name, Inc.
copyright: "Katman Generation"

# title-logo is a neew field that, when used, displays a logo
# instead of custom text. Ideally, image is 50px high and takes up 
#minimal horizontal space. Tested with a new root "images" folder e,g:
title-logo: /images/portfolio-title-logo,png

# Build settings
# renoved minima theme as it is now a regular theme.
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/